#!bin/bash
i=1
inotifywait -m ../images/ -e create -e moved_to |
    while read dir action file; do
        if [ $action == "CREATE" ]; then
          extension="${file##*.}";
          mv "${dir}${file}" "${dir}$((i++)).${extension}";
        fi
    done
